'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('master_volume_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('master_volume_skins').insert([
        {
          id: 1,
          name: 'Master Volume: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 2, 3, 4, 5, 11, 12, 13, 21, 22, 23 ]
          },
          face_path: '../img/january/ice-texture1.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#7DF9FF',
          face_font_color: '#000000',
          face_font_shadow: '#7DF9FF',
          top_path: '../img/january/ice-texture1.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#7DF9FF',
          signal_path: '../img/january/ice-texture1.jpg',
          signal_size: '500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#7DF9FF',
          signal_font_color: '#000000',
          signal_font_shadow: '#7DF9FF',
          display_path: '../img/january/blue_ice.png',
          input_size: '100%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#7DF9FF',
          input_font_color: '#000000',
          input_font_shadow: '#7DF9FF',
          display_span_color: '#fff000',
          gain_display_size: '300%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#7DF9FF',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#7DF9FF',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Master Volume: January B',
          month: 'january',
          rule: {
            "dates": [ 6, 7, 8, 14, 15, 24, 25, 26, 27, 28 ]
          },
          face_path: '../img/january/37772915-Green-Ice-Seamless-and-Tileable-Background-Texture-Stock-Photo.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#8f00ff',
          face_font_color: '#000000',
          face_font_shadow: '#8f00ff',
          top_path: '../img/january/37772915-Green-Ice-Seamless-and-Tileable-Background-Texture-Stock-Photo.jpg',
          top_size: '300%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#8f00ff',
          signal_path: '../img/january/37772915-Green-Ice-Seamless-and-Tileable-Background-Texture-Stock-Photo.jpg',
          signal_size: '800%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#8f00ff',
          signal_font_color: '#000000',
          signal_font_shadow: '#8f00ff',
          display_path: '../img/january/ice_ground_texture_by_hhh316-d5imitg.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#8f00ff',
          input_font_color: '#000000',
          input_font_shadow: '#8f00ff',
          display_span_color: '#8f00ff',
          gain_display_size: '300%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#8f00ff',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#8f00ff',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Master Volume: January C',
          month: 'january',
          rule: {
            "dates": [ 9, 10, 16, 17, 18, 19, 20, 29, 30, 31 ]
          },
          face_path: '../img/january/masterVolumeJancSignal.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#DAA520',
          face_font_color: '#000000',
          face_font_shadow: '#DAA520',
          top_path: '../img/january/masterVolumeJancSignal.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#DAA520',
          signal_path: '../img/january/masterVolumeJancSignal.jpg',
          signal_size: '800%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#DAA520',
          signal_font_color: '#000000',
          signal_font_shadow: '#DAA520',
          display_path: '../img/january/masterVolumeDisplayFace.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#DAA520',
          input_font_color: '#000000',
          input_font_shadow: '#DAA520',
          display_span_color: '#DAA520',
          gain_display_size: '300%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#DAA520',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#DAA520',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Master Volume: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 3, 5, 7, 9, 11, 13, 21, 23 ]
          },
          face_path: '../img/february/red-silk-wallpaper-53919-55650-hd-wallpapers.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#26FF26',
          face_font_color: '#000000',
          face_font_shadow: '#26FF26',
          top_path: '../img/february/Red-Silk-Fabric-Texture.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#26FF26',
          signal_path: '../img/february/Red-Silk-Fabric-Texture.jpg',
          signal_size: '1000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#26FF26',
          signal_font_color: '#000000',
          signal_font_shadow: '#26FF26',
          display_path: '../img/february/240_F_131355372_M07WEabz06WTACSC1aS7S7K9iiJ4QHBc.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#26FF26',
          input_font_color: '#000000',
          input_font_shadow: '#26FF26',
          display_span_color: '#26FF26',
          gain_display_size: '300%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#26FF26',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#26FF26',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Master Volume: February B',
          month: 'february',
          rule: {
            "dates": [ 2, 4, 6, 15, 17, 19, 25, 27, 29, 22 ]
          },
          face_path: '../img/february/cloth_silk_gloss_light_50570_1920x1080.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#FFFE00',
          face_font_color: '#000000',
          face_font_shadow: '#FFFE00',
          top_path: '../img/february/Large_bl-417.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#FFFE00',
          signal_path: '../img/february/Large_bl-417.jpg',
          signal_size: '1000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#FFFE00',
          signal_font_color: '#000000',
          signal_font_shadow: '#FFFE00',
          display_path: '../img/february/Luxury-Backgrounds-4.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#FFFE00',
          input_font_color: '#000000',
          input_font_shadow: '#FFFE00',
          display_span_color: '#FFFE00',
          gain_display_size: '300%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#FFFE00',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#FFFE00',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Master Volume: February C',
          month: 'february',
          rule: {
            "dates": [ 8, 10, 18, 12, 14, 16, 20, 26, 28, 24 ]
          },
          face_path: '../img/february/velvet-texture-plain.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff003f',
          face_font_color: '#000000',
          face_font_shadow: '#ff003f',
          top_path: '../img/february/texture-1289287_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#ff003f',
          signal_path: '../img/february/texture-1289287_1920.jpg',
          signal_size: '1000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff003f',
          signal_font_color: '#000000',
          signal_font_shadow: '#ff003f',
          display_path: '../img/february/2244114966_d11efd03e5.jpg',
          input_size: '1000%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ff003f',
          input_font_color: '#000000',
          input_font_shadow: '#ff003f',
          display_span_color: '#ff003f',
          gain_display_size: '300%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#ff003f',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#ff003f',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 7,
          name: 'Master Volume: March A',
          month: 'march',
          rule: {
            "dates": [ 1, 3, 5, 7, 9, 11, 13, 15, 21, 23 ]
          },
          face_path: '../img/march/g-surf-glass-pr.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#C0C0C0',
          face_font_color: '#000000',
          face_font_shadow: '#C0C0C0',
          top_path: '../img/march/g-surf-zync-pr.jpg',
          top_size: '200%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#C0C0C0',
          signal_path: '../img/march/g-surf-zync-pr.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#C0C0C0',
          signal_font_color: '#000000',
          signal_font_shadow: '#C0C0C0',
          display_path: '../img/march/0520.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#C0C0C0',
          input_font_color: '#000000',
          input_font_shadow: '#C0C0C0',
          display_span_color: '#ff003f',
          gain_display_size: '200%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#C0C0C0',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#C0C0C0',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 8,
          name: 'Master Volume: March B',
          month: 'march',
          rule: {
            "dates": [ 2, 4, 6, 17, 19, 22, 24, 25, 27, 29 ]
          },
          face_path: '../img/march/raindrop-1427952_1920.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff3232',
          face_font_color: '#000000',
          face_font_shadow: '#ff3232',
          top_path: '../img/march/tabitha-732545_1920.jpg',
          top_size: '200%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#ff3232',
          signal_path: '../img/march/tabitha-732545_1920.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff3232',
          signal_font_color: '#000000',
          signal_font_shadow: '#ff3232',
          display_path: '../img/march/glass-1155232_1920.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ff3232',
          input_font_color: '#000000',
          input_font_shadow: '#ff3232',
          display_span_color: '#ff003f',
          gain_display_size: '200%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#ff3232',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#ff3232',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 9,
          name: 'Master Volume: March C',
          month: 'march',
          rule: {
            "dates": [ 8, 10, 12, 14, 16, 18, 20, 26, 28, 30 ]
          },
          face_path: '../img/march/1509224908-12088-1.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ccccff',
          face_font_color: '#000000',
          face_font_shadow: '#ccccff',
          top_path: '../img/march/WindowsBlocks0021_1_600.jpg',
          top_size: '200%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#ccccff',
          signal_path: '../img/march/WindowsBlocks0021_1_600.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ccccff',
          signal_font_color: '#000000',
          signal_font_shadow: '#ccccff',
          display_path: '../img/march/Tikkurila_Taika_Paint_silver.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ccccff',
          input_font_color: '#000000',
          input_font_shadow: '#ccccff',
          display_span_color: '#ff003f',
          gain_display_size: '200%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#ccccff',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#ccccff',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 10,
          name: 'Master Volume: April A',
          month: 'april',
          rule: {
            "dates": [ 1, 3, 5, 7, 9, 11, 13, 15, 21, 23 ]
          },
          face_path: '../img/april/heart-3367962_1920.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ccbadc',
          face_font_color: '#000000',
          face_font_shadow: '#ccbadc',
          top_path: '../img/april/lake-2120033_1920.jpg',
          top_size: '200%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#ccbadc',
          signal_path: '../img/april/lake-2120033_1920.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ccbadc',
          signal_font_color: '#000000',
          signal_font_shadow: '#ccbadc',
          display_path: '../img/april/water-1330252_1920.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ccbadc',
          input_font_color: '#000000',
          input_font_shadow: '#ccbadc',
          display_span_color: '#ffb2b2',
          gain_display_size: '200%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#ccbadc',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#ccbadc',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 11,
          name: 'Master Volume: April B',
          month: 'april',
          rule: {
            "dates": [ 2, 4, 6, 17, 19, 22, 24, 25, 27, 29 ]
          },
          face_path: '../img/april/krystian-tambur-101317-unsplash.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#99e099',
          face_font_color: '#000000',
          face_font_shadow: '#99e099',
          top_path: '../img/april/manu-schwendener-39728-unsplash.jpg',
          top_size: '200%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#99e099',
          signal_path: '../img/april/manu-schwendener-39728-unsplash.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#99e099',
          signal_font_color: '#000000',
          signal_font_shadow: '#99e099',
          display_path: '../img/april/freestocks-org-251801-unsplash.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#99e099',
          input_font_color: '#000000',
          input_font_shadow: '#99e099',
          display_span_color: '#ffb2b2',
          gain_display_size: '200%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#99e099',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#99e099',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 12,
          name: 'Master Volume: April C',
          month: 'april',
          rule: {
            "dates": [ 8, 10, 12, 14, 15, 18, 20, 26, 28, 30 ]
          },
          face_path: '../img/april/johannes-w-332636-unsplash.jpg',
          face_size: '150%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffc966',
          face_font_color: '#000000',
          face_font_shadow: '#ffc966',
          top_path: '../img/april/paul-bulai-448085-unsplash.jpg',
          top_size: '200%',
          top_repeat: 'no-repeat',
          top_font_color: '#000000',
          top_font_shadow: '#ffc966',
          signal_path: '../img/april/paul-bulai-448085-unsplash.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffc966',
          signal_font_color: '#000000',
          signal_font_shadow: '#ffc966',
          display_path: '../img/april/jarrod-reed-401911-unsplash.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ffc966',
          input_font_color: '#000000',
          input_font_shadow: '#ffc966',
          display_span_color: '#ffb2b2',
          gain_display_size: '200%',
          gain_display_repeat: 'no-repeat',
          gain_display_box_shadow_color: '#ffc966',
          gain_display_font_color: '#000000',
          master_volume_size: '300%',
          master_volume_repeat: 'no-repeat',
          master_volume_box_shadow: '#ffc966',
          slider_background_image: '../img/noun_149738_cc.png',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('master_volume_skins_id_seq', (SELECT MAX(id) FROM master_volume_skins));");
    });
};
