'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('dynamic_compressor_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('dynamic_compressor_skins').insert([
        {
          id: 1,
          name: 'Dynamic Compressor: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 7, 8, 9, 10, 11, 19, 20, 21, 30, 31 ]
          },
          face_path: '../img/january/dynCompressorFaceA.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#8c92ac',
          face_font_color: '#ff0180',
          face_font_shadow: '#8c92ac',
          top_path: '../img/january/dynamicCompressorTopJanA.jpg',
          top_size: '210%',
          top_repeat: 'no-repeat',
          top_font_color: '#ff0180',
          top_font_shadow: '#8c92ac',
          signal_path: '../img/january/dynamicCompressorTopJanA.jpg',
          signal_size: '1300%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#8c92ac',
          signal_font_color: '#ff0180',
          signal_font_shadow: '#8c92ac',
          display_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#8c92ac',
          output_font_color: '#ff0180',
          output_font_shadow: '#8c92ac',
          threshold_display_size: '300%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#8c92ac',
          threshold_display_font_color: '#ff0180',
          threshold_slider_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#8c92ac',
          knee_display_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          knee_display_size: '300%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#8c92ac',
          knee_display_font_color: '#ff0180',
          knee_slider_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#8c92ac',
          ratio_display_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          ratio_display_size: '300%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#8c92ac',
          ratio_display_font_color: '#ff0180',
          ratio_slider_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#8c92ac',
          attack_display_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          attack_display_size: '300%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#8c92ac',
          attack_display_font_color: '#ff0180',
          attack_slider_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#8c92ac',
          release_display_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          release_display_size: '300%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#8c92ac',
          release_display_font_color: '#ff0180',
          release_slider_path: '../img/january/dynamicCompressorDisplayJanA.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#8c92ac',
          slider_shader_color_1: '#fff000',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Dynamic Compressor: January B',
          month: 'january',
          rule: {
            "dates": [ 4, 5, 6, 17, 18, 25, 26, 27, 28, 29 ]
          },
          face_path: '../img/january/dynamicCompressorJanB.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#191900',
          face_font_color: '#00ff00',
          face_font_shadow: '#191900',
          top_path: '../img/january/dynamicCompressorJanbTop.jpg',
          top_size: '210%',
          top_repeat: 'no-repeat',
          top_font_color: '#00ff00',
          top_font_shadow: '#191900',
          signal_path: '../img/january/dynamicCompressorJanbTop.jpg',
          signal_size: '1300%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#191900',
          signal_font_color: '#00ff00',
          signal_font_shadow: '#191900',
          display_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#191900',
          output_font_color: '#00ff00',
          output_font_shadow: '#191900',
          threshold_display_size: '300%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#191900',
          threshold_display_font_color: '#00ff00',
          threshold_slider_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#191900',
          knee_display_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          knee_display_size: '300%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#191900',
          knee_display_font_color: '#00ff00',
          knee_slider_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#191900',
          ratio_display_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          ratio_display_size: '300%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#191900',
          ratio_display_font_color: '#00ff00',
          ratio_slider_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#191900',
          attack_display_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          attack_display_size: '300%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#191900',
          attack_display_font_color: '#00ff00',
          attack_slider_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#191900',
          release_display_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          release_display_size: '300%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#191900',
          release_display_font_color: '#00ff00',
          release_slider_path: '../img/january/dynamicCompressorJanbDisplay.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#191900',
          slider_shader_color_1: '#fff000',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Dynamic Compressor: January C',
          month: 'january',
          rule: {
            "dates": [ 2, 3, 12, 13, 14, 15, 16, 22, 23, 24 ]
          },
          face_path: '../img/january/winter-ice-frost-glass-window-pattern-wallpaper-scenes-free-1920x1080.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#8B0000',
          face_font_color: '#00FFFF',
          face_font_shadow: '#8B0000',
          top_path: '../img/january/dynamicCompressorTopJanc.jpg',
          top_size: '210%',
          top_repeat: 'no-repeat',
          top_font_color: '#00FFFF',
          top_font_shadow: '#8B0000',
          signal_path: '../img/january/dynamicCompressorTopJanc.jpg',
          signal_size: '1300%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#8B0000',
          signal_font_color: '#00FFFF',
          signal_font_shadow: '#8B0000',
          display_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#8B0000',
          output_font_color: '#00FFFF',
          output_font_shadow: '#8B0000',
          threshold_display_size: '300%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#8B0000',
          threshold_display_font_color: '#00FFFF',
          threshold_slider_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#8B0000',
          knee_display_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          knee_display_size: '300%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#8B0000',
          knee_display_font_color: '#00FFFF',
          knee_slider_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#8B0000',
          ratio_display_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          ratio_display_size: '300%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#8B0000',
          ratio_display_font_color: '#00FFFF',
          ratio_slider_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#8B0000',
          attack_display_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          attack_display_size: '300%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#8B0000',
          attack_display_font_color: '#00FFFF',
          attack_slider_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#8B0000',
          release_display_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          release_display_size: '300%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#8B0000',
          release_display_font_color: '#00FFFF',
          release_slider_path: '../img/january/dynamicCompressorDisplayJanc.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#8B0000',
          slider_shader_color_1: '#FF4500',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Dynamic Compressor: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 2, 3, 4, 5, 11, 12, 13, 21, 22 ]
          },
          face_path: '../img/february/44b6ff916e415e6da012606cec636439.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffff32',
          face_font_color: '#191900',
          face_font_shadow: '#ffff32',
          top_path: '../img/february/red-velvet-texture-to-background-41175781.jpg',
          top_size: '210%',
          top_repeat: 'no-repeat',
          top_font_color: '#191900',
          top_font_shadow: '#ffff32',
          signal_path: '../img/february/red-velvet-texture-to-background-41175781.jpg',
          signal_size: '1400%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffff32',
          signal_font_color: '#191900',
          signal_font_shadow: '#ffff32',
          display_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ffff32',
          output_font_color: '#191900',
          output_font_shadow: '#ffff32',
          threshold_display_size: '300%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#ffff32',
          threshold_display_font_color: '#191900',
          threshold_slider_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#ffff32',
          knee_display_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          knee_display_size: '300%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#ffff32',
          knee_display_font_color: '#191900',
          knee_slider_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#ffff32',
          ratio_display_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          ratio_display_size: '300%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#ffff32',
          ratio_display_font_color: '#191900',
          ratio_slider_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#ffff32',
          attack_display_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          attack_display_size: '300%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#ffff32',
          attack_display_font_color: '#191900',
          attack_slider_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#ffff32',
          release_display_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          release_display_size: '300%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#ffff32',
          release_display_font_color: '#191900',
          release_slider_path: '../img/february/BH_VelvetTexA-550x550.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#ffff32',
          slider_shader_color_1: '#666600',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Dynamic Compressor: February B',
          month: 'february',
          rule: {
            "dates": [ 6, 7, 8, 14, 15, 23, 24, 25, 26, 27 ]
          },
          face_path: '../img/february/maxresdefault.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#0000b2',
          face_font_color: '#ccccff',
          face_font_shadow: '#0000b2',
          top_path: '../img/february/dynamiccompressortopsilkb.jpeg',
          top_size: '210%',
          top_repeat: 'no-repeat',
          top_font_color: '#ccccff',
          top_font_shadow: '#0000b2',
          signal_path: '../img/february/dynamiccompressortopsilkb.jpeg',
          signal_size: '1400%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#0000b2',
          signal_font_color: '#ccccff',
          signal_font_shadow: '#0000b2',
          display_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#0000b2',
          output_font_color: '#ccccff',
          output_font_shadow: '#0000b2',
          threshold_display_size: '300%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#0000b2',
          threshold_display_font_color: '#ccccff',
          threshold_slider_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#0000b2',
          knee_display_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          knee_display_size: '300%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#0000b2',
          knee_display_font_color: '#ccccff',
          knee_slider_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#0000b2',
          ratio_display_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          ratio_display_size: '300%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#0000b2',
          ratio_display_font_color: '#ccccff',
          ratio_slider_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#0000b2',
          attack_display_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          attack_display_size: '300%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#0000b2',
          attack_display_font_color: '#ccccff',
          attack_slider_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#0000b2',
          release_display_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          release_display_size: '300%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#0000b2',
          release_display_font_color: '#ccccff',
          release_slider_path: '../img/february/satin-smooth-purple-vector-background-800x566.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#0000b2',
          slider_shader_color_1: '#3232ff',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Dynamic Compressor: February C',
          month: 'february',
          rule: {
            "dates": [ 9, 10, 16, 17, 18, 19, 20, 28, 29 ]
          },
          face_path: '../img/february/rust_2_of_2_.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#e50000',
          face_font_color: '#FFE5E5',
          face_font_shadow: '#e50000',
          top_path: '../img/february/crepebacksatin40-f.jpeg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#FFE5E5',
          top_font_shadow: '#e50000',
          signal_path: '../img/february/crepebacksatin40-f.jpeg',
          signal_size: '1400%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#e50000',
          signal_font_color: '#FFE5E5',
          signal_font_shadow: '#e50000',
          display_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#e50000',
          output_font_color: '#FFE5E5',
          output_font_shadow: '#e50000',
          threshold_display_size: '300%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#e50000',
          threshold_display_font_color: '#FFE5E5',
          threshold_slider_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#e50000',
          knee_display_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          knee_display_size: '300%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#e50000',
          knee_display_font_color: '#FFE5E5',
          knee_slider_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#e50000',
          ratio_display_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          ratio_display_size: '300%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#e50000',
          ratio_display_font_color: '#FFE5E5',
          ratio_slider_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#e50000',
          attack_display_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          attack_display_size: '300%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#e50000',
          attack_display_font_color: '#FFE5E5',
          attack_slider_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#e50000',
          release_display_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          release_display_size: '300%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#e50000',
          release_display_font_color: '#FFE5E5',
          release_slider_path: '../img/february/il_340x270.1247723925_r14m.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#e50000',
          slider_shader_color_1: '#190000',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 7,
          name: 'Dynamic Compressor: March A',
          month: 'march',
          rule: {
            "dates": [ 1, 2, 3, 4, 5, 11, 12, 13, 21, 22, 31 ]
          },
          face_path: '../img/march/architecture-3310018_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#7fff7f',
          face_font_color: '#001900',
          face_font_shadow: '#7fff7f',
          top_path: '../img/march/a-glass-of-3287791_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#001900',
          top_font_shadow: '#7fff7f',
          signal_path: '../img/march/a-glass-of-3287791_1920.jpg',
          signal_size: '1400%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#7fff7f',
          signal_font_color: '#001900',
          signal_font_shadow: '#7fff7f',
          display_path: '../img/march/frosted-glass-2360088_1920.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#7fff7f',
          output_font_color: '#001900',
          output_font_shadow: '#7fff7f',
          threshold_display_size: '100%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#7fff7f',
          threshold_display_font_color: '#001900',
          threshold_slider_path: '../img/march/frosted-glass-2360088_1920.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#7fff7f',
          knee_display_path: '../img/march/frosted-glass-2360088_1920.jpg',
          knee_display_size: '100%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#7fff7f',
          knee_display_font_color: '#001900',
          knee_slider_path: '../img/march/frosted-glass-2360088_1920.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#7fff7f',
          ratio_display_path: '../img/march/frosted-glass-2360088_1920.jpg',
          ratio_display_size: '100%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#7fff7f',
          ratio_display_font_color: '#001900',
          ratio_slider_path: '../img/march/frosted-glass-2360088_1920.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#7fff7f',
          attack_display_path: '../img/march/frosted-glass-2360088_1920.jpg',
          attack_display_size: '100%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#7fff7f',
          attack_display_font_color: '#001900',
          attack_slider_path: '../img/march/frosted-glass-2360088_1920.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#7fff7f',
          release_display_path: '../img/march/frosted-glass-2360088_1920.jpg',
          release_display_size: '100%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#7fff7f',
          release_display_font_color: '#001900',
          release_slider_path: '../img/march/frosted-glass-2360088_1920.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#7fff7f',
          slider_shader_color_1: '#004c00',
          slider_shader_color_2: '#b2ffb2',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 8,
          name: 'Dynamic Compressor: March B',
          month: 'march',
          rule: {
            "dates": [ 6, 7, 8, 14, 15, 23, 24, 25, 26, 27 ]
          },
          face_path: '../img/march/alex-loup-393837-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#a31919',
          face_font_color: '#0f0000',
          face_font_shadow: '#a31919',
          top_path: '../img/march/luana-azevedo-488474-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#0f0000',
          top_font_shadow: '#a31919',
          signal_path: '../img/march/luana-azevedo-488474-unsplash.jpg',
          signal_size: '1400%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#a31919',
          signal_font_color: '#0f0000',
          signal_font_shadow: '#a31919',
          display_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          output_size: '300%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#a31919',
          output_font_color: '#0f0000',
          output_font_shadow: '#a31919',
          threshold_display_size: '100%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#a31919',
          threshold_display_font_color: '#0f0000',
          threshold_slider_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#a31919',
          knee_display_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          knee_display_size: '100%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#a31919',
          knee_display_font_color: '#0f0000',
          knee_slider_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#a31919',
          ratio_display_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          ratio_display_size: '100%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#a31919',
          ratio_display_font_color: '#0f0000',
          ratio_slider_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#a31919',
          attack_display_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          attack_display_size: '100%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#a31919',
          attack_display_font_color: '#0f0000',
          attack_slider_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#a31919',
          release_display_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          release_display_size: '100%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#a31919',
          release_display_font_color: '#0f0000',
          release_slider_path: '../img/march/daniel-van-den-berg-420571-unsplash.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#a31919',
          slider_shader_color_1: '#ad3232',
          slider_shader_color_2: '#f4e5e5',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 9,
          name: 'Dynamic Compressor: March C',
          month: 'march',
          rule: {
            "dates": [ 9, 10, 16, 17, 18, 19, 20, 28, 29, 30 ]
          },
          face_path: '../img/march/makarios-tang-605356-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#a5a5ff',
          face_font_color: '#070719',
          face_font_shadow: '#a5a5ff',
          top_path: '../img/march/paolo-nicolello-695167-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#070719',
          top_font_shadow: '#a5a5ff',
          signal_path: '../img/march/paolo-nicolello-695167-unsplash.jpg',
          signal_size: '1400%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#a5a5ff',
          signal_font_color: '#070719',
          signal_font_shadow: '#a5a5ff',
          display_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          output_size: '300%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#a5a5ff',
          output_font_color: '#070719',
          output_font_shadow: '#a5a5ff',
          threshold_display_size: '100%',
          threshold_display_repeat: 'no-repeat',
          threshold_display_box_shadow_color: '#a5a5ff',
          threshold_display_font_color: '#070719',
          threshold_slider_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          threshold_slider_size: '300%',
          threshold_slider_repeat: 'no-repeat',
          threshold_slider_box_shadow_color: '#a5a5ff',
          knee_display_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          knee_display_size: '100%',
          knee_repeat: 'no-repeat',
          knee_box_shadow: '#a5a5ff',
          knee_display_font_color: '#070719',
          knee_slider_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          knee_slider_size: '300%',
          knee_slider_repeat: 'no-repeat',
          knee_slider_box_shadow: '#a5a5ff',
          ratio_display_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          ratio_display_size: '100%',
          ratio_display_repeat: 'no-repeat',
          ratio_display_box_shadow_color: '#a5a5ff',
          ratio_display_font_color: '#070719',
          ratio_slider_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          ratio_slider_size: '300%',
          ratio_slider_repeat: 'no-repeat',
          ratio_slider_box_shadow_color: '#a5a5ff',
          attack_display_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          attack_display_size: '100%',
          attack_display_repeat: 'no-repeat',
          attack_display_box_shadow_color: '#a5a5ff',
          attack_display_font_color: '#070719',
          attack_slider_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          attack_slider_size: '300%',
          attack_slider_repeat: 'no-repeat',
          attack_slider_box_shadow_color: '#a5a5ff',
          release_display_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          release_display_size: '100%',
          release_display_repeat: 'no-repeat',
          release_display_box_shadow_color: '#a5a5ff',
          release_display_font_color: '#070719',
          release_slider_path: '../img/march/chuttersnap-733758-unsplash.jpg',
          release_slider_size: '300%',
          release_slider_repeat: 'no-repeat',
          release_slider_box_shadow_color: '#a5a5ff',
          slider_shader_color_1: '#26267f',
          slider_shader_color_2: '#ededff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('dynamic_compressor_skins_id_seq', (SELECT MAX(id) FROM dynamic_compressor_skins));");
    });
};
