'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('envelope_generator_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('envelope_generator_skins').insert([
        {
          id: 1,
          name: 'Envelope Generator: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 3, 4, 7, 10, 11, 14, 17, 21, 24, 31 ]
          },
          face_path: '../img/january/an-abstract-of-cracked-arctic-sea-ice-carsten-peter.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#999900',
          face_font_color: '#190000',
          face_font_shadow_color: '#999900',
          top_path: '../img/january/ice-floe-winter-nature-pattern-background-floes-floating-water-surface-freezing-lake-texture-abstract-39416586.jpg',
          top_size: '150%',
          top_repeat: 'no-repeat',
          top_font_color: '#190000',
          top_font_shadow_color: '#999900',
          signal_path: '../img/january/ice-floe-winter-nature-pattern-background-floes-floating-water-surface-freezing-lake-texture-abstract-39416586.jpg',
          signal_size: '1300%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#999900',
          signal_font_color: '#190000',
          signal_font_shadow_color: '#999900',
          vertical_meter_background_color: '#A9A9A9',
          vertical_meter_outline_background_color: '#eeeeee',
          vertical_meter_shadow_color: '#999900',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#999900',
          output_font_color: '#190000',
          envelope_input_display_path: '../img/january/18e2fca5234f5d52bc44401c5d53c5d4.png',
          envelope_input_display_size: '600%',
          envelope_input_display_repeat: 'no-repeat',
          slope_amount_path: '../img/january/18e2fca5234f5d52bc44401c5d53c5d4.png',
          slope_amount_size: '300%',
          slope_amount_repeat: 'no-repeat',
          release_slope_amount_path: '../img/january/18e2fca5234f5d52bc44401c5d53c5d4.png',
          release_slope_amount_size: '300%',
          release_slope_amount_repeat: 'no-repeat',
          decay_slope_amount_path: '../img/january/18e2fca5234f5d52bc44401c5d53c5d4.png',
          decay_slope_amount_size: '300%',
          decay_slope_amount_repeat: 'no-repeat',
          post_sustain_slope_amount_path: '../img/january/18e2fca5234f5d52bc44401c5d53c5d4.png',
          post_sustain_slope_amount_size: '300%',
          post_sustain_slope_amount_repeat: 'no-repeat',
          slider_shader_color_1: '#a1ff66',
          slider_shader_color_2: '#ffffff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Envelope Generator: January B',
          month: 'january',
          rule: {
            "dates": [ 2, 5, 8, 13, 20, 23, 26, 27, 29, 30 ]
          },
          face_path: '../img/january/Ice_web_0.png',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#FF4500',
          face_font_color: '#190000',
          face_font_shadow_color: '#FF4500',
          top_path: '../img/january/texture_43_by_sirius_sdz-d1m50rh.jpg',
          top_size: '150%',
          top_repeat: 'no-repeat',
          top_font_color: '#FF4500',
          top_font_shadow_color: '#FF4500',
          signal_path: '../img/january/texture_43_by_sirius_sdz-d1m50rh.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#FF4500',
          signal_font_color: '#190000',
          signal_font_shadow_color: '#FF4500',
          vertical_meter_background_color: '#A9A9A9',
          vertical_meter_outline_background_color: '#000000',
          vertical_meter_shadow_color: '#FF4500',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#FF4500',
          output_font_color: '#190000',
          envelope_input_display_path: '../img/january/ice_texture_by_cloudhunter.jpg',
          envelope_input_display_size: '600%',
          envelope_input_display_repeat: 'no-repeat',
          slope_amount_path: '../img/january/ice_texture_by_cloudhunter.jpg',
          slope_amount_size: '300%',
          slope_amount_repeat: 'no-repeat',
          release_slope_amount_path: '../img/january/ice_texture_by_cloudhunter.jpg',
          release_slope_amount_size: '300%',
          release_slope_amount_repeat: 'no-repeat',
          decay_slope_amount_path: '../img/january/ice_texture_by_cloudhunter.jpg',
          decay_slope_amount_size: '300%',
          decay_slope_amount_repeat: 'no-repeat',
          post_sustain_slope_amount_path: '../img/january/ice_texture_by_cloudhunter.jpg',
          post_sustain_slope_amount_size: '300%',
          post_sustain_slope_amount_repeat: 'no-repeat',
          slider_shader_color_1: '#FF6347',
          slider_shader_color_2: '#ffffff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Envelope Generator: January C',
          month: 'january',
          rule: {
            "dates": [ 6, 9, 12, 15, 16, 18, 19, 22, 25, 28 ]
          },
          face_path: '../img/january/crystal-blue-inside-the-ice-cave-1024x683.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ADFF2F',
          face_font_color: '#190000',
          face_font_shadow_color: '#ADFF2F',
          top_path: '../img/january/blueIceText.jpeg',
          top_size: '150%',
          top_repeat: 'no-repeat',
          top_font_color: '#190000',
          top_font_shadow_color: '#ADFF2F',
          signal_path: '../img/january/blueIceText.jpeg',
          signal_size: '1800%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ADFF2F',
          signal_font_color: '#190000',
          signal_font_shadow_color: '#ADFF2F',
          vertical_meter_background_color: '#A9A9A9',
          vertical_meter_outline_background_color: '#eeeeee',
          vertical_meter_shadow_color: '#ADFF2F',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ADFF2F',
          output_font_color: '#190000',
          envelope_input_display_path: '../img/january/blueQuartz.jpg',
          envelope_input_display_size: '600%',
          envelope_input_display_repeat: 'no-repeat',
          slope_amount_path: '../img/january/blueQuartz.jpg',
          slope_amount_size: '300%',
          slope_amount_repeat: 'no-repeat',
          release_slope_amount_path: '../img/january/blueQuartz.jpg',
          release_slope_amount_size: '300%',
          release_slope_amount_repeat: 'no-repeat',
          decay_slope_amount_path: '../img/january/blueQuartz.jpg',
          decay_slope_amount_size: '300%',
          decay_slope_amount_repeat: 'no-repeat',
          post_sustain_slope_amount_path: '../img/january/blueQuartz.jpg',
          post_sustain_slope_amount_size: '300%',
          post_sustain_slope_amount_repeat: 'no-repeat',
          slider_shader_color_1: '#FFFFCC',
          slider_shader_color_2: '#ffffff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Envelope Generator: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 3, 5, 6, 9, 11, 15, 19, 21, 25 ]
          },
          face_path: '../img/february/7339591-Fragment-of-red-chinese-silk-with-golden-dragons-and-flowers-Stock-Photo.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffff32',
          face_font_color: '#33330a',
          face_font_shadow_color: '#ffff32',
          top_path: '../img/february/9th_january_201801650.jpg',
          top_size: '150%',
          top_repeat: 'no-repeat',
          top_font_color: '#33330a',
          top_font_shadow_color: '#ffff32',
          signal_path: '../img/february/9th_january_201801650.jpg',
          signal_size: '1300%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffff32',
          signal_font_color: '#33330a',
          signal_font_shadow_color: '#ffff32',
          vertical_meter_background_color: '#A9A9A9',
          vertical_meter_outline_background_color: '#eeeeee',
          vertical_meter_shadow_color: '#ffff32',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ffff32',
          output_font_color: '#33330a',
          envelope_input_display_path: '../img/february/blue-silk-fabric-website-background1.gif',
          envelope_input_display_size: '600%',
          envelope_input_display_repeat: 'no-repeat',
          slope_amount_path: '../img/february/blue-silk-fabric-website-background1.gif',
          slope_amount_size: '300%',
          slope_amount_repeat: 'no-repeat',
          release_slope_amount_path: '../img/february/blue-silk-fabric-website-background1.gif',
          release_slope_amount_size: '300%',
          release_slope_amount_repeat: 'no-repeat',
          decay_slope_amount_path: '../img/february/blue-silk-fabric-website-background1.gif',
          decay_slope_amount_size: '300%',
          decay_slope_amount_repeat: 'no-repeat',
          post_sustain_slope_amount_path: '../img/february/blue-silk-fabric-website-background1.gif',
          post_sustain_slope_amount_size: '300%',
          post_sustain_slope_amount_repeat: 'no-repeat',
          slider_shader_color_1: '#FFFFCC',
          slider_shader_color_2: '#ffffd6',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Envelope Generator: February B',
          month: 'february',
          rule: {
            "dates": [ 4, 8, 10, 13, 16, 22, 23, 25, 27, 29 ]
          },
          face_path: '../img/february/s-kinsaiyuzen010-1.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#7fff7f',
          face_font_color: '#001900',
          face_font_shadow_color: '#7fff7f',
          top_path: '../img/february/O04.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#001900',
          top_font_shadow_color: '#7fff7f',
          signal_path: '../img/february/O04.jpg',
          signal_size: '1300%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#7fff7f',
          signal_font_color: '#001900',
          signal_font_shadow_color: '#7fff7f',
          vertical_meter_background_color: '#A9A9A9',
          vertical_meter_outline_background_color: '#eeeeee',
          vertical_meter_shadow_color: '#7fff7f',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#7fff7f',
          output_font_color: '#001900',
          envelope_input_display_path: '../img/february/khaki-floral-print-vintage-kimono-japanese-silk-3.jpg',
          envelope_input_display_size: '600%',
          envelope_input_display_repeat: 'no-repeat',
          slope_amount_path: '../img/february/khaki-floral-print-vintage-kimono-japanese-silk-3.jpg',
          slope_amount_size: '300%',
          slope_amount_repeat: 'no-repeat',
          release_slope_amount_path: '../img/february/khaki-floral-print-vintage-kimono-japanese-silk-3.jpg',
          release_slope_amount_size: '300%',
          release_slope_amount_repeat: 'no-repeat',
          decay_slope_amount_path: '../img/february/khaki-floral-print-vintage-kimono-japanese-silk-3.jpg',
          decay_slope_amount_size: '300%',
          decay_slope_amount_repeat: 'no-repeat',
          post_sustain_slope_amount_path: '../img/february/khaki-floral-print-vintage-kimono-japanese-silk-3.jpg',
          post_sustain_slope_amount_size: '300%',
          post_sustain_slope_amount_repeat: 'no-repeat',
          slider_shader_color_1: '#99ff99',
          slider_shader_color_2: '#006600',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Envelope Generator: February C',
          month: 'february',
          rule: {
            "dates": [ 2, 7, 12, 14, 17, 18, 20, 24, 26, 28 ]
          },
          face_path: '../img/february/rawpixel-569613-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff3232',
          face_font_color: '#001900',
          face_font_shadow_color: '#ff3232',
          top_path: '../img/february/francisco-mamani-468426-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#001900',
          top_font_shadow_color: '#ff3232',
          signal_path: '../img/february/francisco-mamani-468426-unsplash.jpg',
          signal_size: '1300%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff3232',
          signal_font_color: '#001900',
          signal_font_shadow_color: '#ff3232',
          vertical_meter_background_color: '#A9A9A9',
          vertical_meter_outline_background_color: '#eeeeee',
          vertical_meter_shadow_color: '#ff3232',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ff3232',
          output_font_color: '#001900',
          envelope_input_display_path: '../img/february/sylvie-tittel-726553-unsplash.jpg',
          envelope_input_display_size: '600%',
          envelope_input_display_repeat: 'no-repeat',
          slope_amount_path: '../img/february/sylvie-tittel-726553-unsplash.jpg',
          slope_amount_size: '300%',
          slope_amount_repeat: 'no-repeat',
          release_slope_amount_path: '../img/february/sylvie-tittel-726553-unsplash.jpg',
          release_slope_amount_size: '300%',
          release_slope_amount_repeat: 'no-repeat',
          decay_slope_amount_path: '../img/february/sylvie-tittel-726553-unsplash.jpg',
          decay_slope_amount_size: '300%',
          decay_slope_amount_repeat: 'no-repeat',
          post_sustain_slope_amount_path: '../img/february/sylvie-tittel-726553-unsplash.jpg',
          post_sustain_slope_amount_size: '300%',
          post_sustain_slope_amount_repeat: 'no-repeat',
          slider_shader_color_1: '#7f1919',
          slider_shader_color_2: '#006600',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('envelope_generator_skins_id_seq', (SELECT MAX(id) FROM envelope_generator_skins));");
    });
};
