'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('weather_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('weather_skins').insert([
        {
          id: 1,
          name: 'Weather Module: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 3, 4, 7, 10, 11, 14, 17, 21, 24, 31 ]
          },
          face_path: '../img/january/wattex-1.jpg',
          face_size: '200%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#FFDF00',
          face_font_color: '#006400',
          face_font_shadow_color: '#FFDF00',
          top_path: '../img/january/ice_texture_viii_by_melyssah6_stock-d3h8bf2.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#006400',
          top_font_shadow_color: '#FFDF00',
          signal_path: '../img/january/ice_texture_viii_by_melyssah6_stock-d3h8bf2.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#FFDF00',
          signal_font_color: '#006400',
          signal_font_shadow_color: '#FFDF00',
          input_path: '../img/january/iceberg-background-28129523.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          zip_user_input_path: '../img/january/iceberg-background-28129523.jpg',
          zip_user_input_size: '300%',
          zip_user_input_repeat: 'no-repeat',
          zip_modulator_text_shadow_color: '#FFDF00',
          block_path: '../img/january/iceberg-background-28129523.jpg',
          block_size: '300%',
          block_repeat: 'no-repeat',
          block_box_shadow_color: '#FFDF00',
          block_font_color: '#006400',
          webcam_block_path: '../img/january/iceberg-background-28129523.jpg',
          webcam_block_display_size: '200%',
          webcam_block_repeat: 'no-repeat',
          webcam_block_box_shadow_color: '#FFDF00',
          slider_shader_color_1: '#EEE8AA',
          slider_shader_color_2: '#ffffff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Weather Module: January B',
          month: 'january',
          rule: {
            "dates": [ 2, 6, 9, 13, 20, 23, 26, 27, 29, 30 ]
          },
          face_path: '../img/january/4619713941_fd4701b7d1.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff4c4c',
          face_font_color: '#330000',
          face_font_shadow_color: '#ff4c4c',
          top_path: '../img/january/flake.jpeg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#330000',
          top_font_shadow_color: '#ff4c4c',
          signal_path: '../img/january/flake.jpeg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff4c4c',
          signal_font_color: '#330000',
          signal_font_shadow_color: '#ff4c4c',
          input_path: '../img/january/Cold-Ice-Texture-by-Jordan-Hubbard.jpg',
          input_size: '600',
          input_repeat: 'no-repeat',
          zip_user_input_path: '../img/january/Cold-Ice-Texture-by-Jordan-Hubbard.jpg',
          zip_user_input_size: '300%',
          zip_user_input_repeat: 'no-repeat',
          zip_modulator_text_shadow_color: '#ff4c4c',
          block_path: '../img/january/Cold-Ice-Texture-by-Jordan-Hubbard.jpg',
          block_size: '300%',
          block_repeat: 'no-repeat',
          block_box_shadow_color: '#ff4c4c',
          block_font_color: '#330000',
          webcam_block_path: '../img/january/Cold-Ice-Texture-by-Jordan-Hubbard.jpg',
          webcam_block_display_size: '200%',
          webcam_block_repeat: 'no-repeat',
          webcam_block_box_shadow_color: '#ff4c4c',
          slider_shader_color_1: '#FF7F7F',
          slider_shader_color_2: '#ffffff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Weather Module: January C',
          month: 'january',
          rule: {
            "dates": [ 5, 8, 12, 15, 16, 18, 19, 22, 25, 28 ]
          },
          face_path: '../img/january/iceshelf_01.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#daff99',
          face_font_color: '#203300',
          face_font_shadow_color: '#daff99',
          top_path: '../img/january/4074902.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#203300',
          top_font_shadow_color: '#daff99',
          signal_path: '../img/january/4074902.jpg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#daff99',
          signal_font_color: '#203300',
          signal_font_shadow_color: '#daff99',
          input_path: '../img/january/greenland_ali_2016167_lrg.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          zip_user_input_path: '../img/january/greenland_ali_2016167_lrg.jpg',
          zip_user_input_size: '300%',
          zip_user_input_repeat: 'no-repeat',
          zip_modulator_text_shadow_color: '#daff99',
          block_path: '../img/january/greenland_ali_2016167_lrg.jpg',
          block_size: '300%',
          block_repeat: 'no-repeat',
          block_box_shadow_color: '#daff99',
          block_font_color: '#203300',
          webcam_block_path: '../img/january/greenland_ali_2016167_lrg.jpg',
          webcam_block_display_size: '200%',
          webcam_block_repeat: 'no-repeat',
          webcam_block_box_shadow_color: '#daff99',
          slider_shader_color_1: '#72b200',
          slider_shader_color_2: '#ffffff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Weather Module: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 3, 5, 9, 11, 15, 19, 21, 25 ]
          },
          face_path: '../img/february/1501-Red-velvet-couch-texture.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#3232ff',
          face_font_color: '#000019',
          face_font_shadow_color: '#3232ff',
          top_path: '../img/february/0000072_bronze-green-crushed_275.jpeg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#000019',
          top_font_shadow_color: '#3232ff',
          signal_path: '../img/february/0000072_bronze-green-crushed_275.jpeg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#3232ff',
          signal_font_color: '#000019',
          signal_font_shadow_color: '#3232ff',
          input_path: '../img/february/arthouse-romeo-damask-pattern-wallpaper-modern-metallic-floral-motif-p3592-image-victorian-flock-velvet-textured-patterns-blue-suzette-grey-970x970.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          zip_user_input_path: '../img/february/arthouse-romeo-damask-pattern-wallpaper-modern-metallic-floral-motif-p3592-image-victorian-flock-velvet-textured-patterns-blue-suzette-grey-970x970.jpg',
          zip_user_input_size: '300%',
          zip_user_input_repeat: 'no-repeat',
          zip_modulator_text_shadow_color: '#3232ff',
          block_path: '../img/february/arthouse-romeo-damask-pattern-wallpaper-modern-metallic-floral-motif-p3592-image-victorian-flock-velvet-textured-patterns-blue-suzette-grey-970x970.jpg',
          block_size: '300%',
          block_repeat: 'no-repeat',
          block_box_shadow_color: '#3232ff',
          block_font_color: '#000019',
          webcam_block_path: '../img/february/arthouse-romeo-damask-pattern-wallpaper-modern-metallic-floral-motif-p3592-image-victorian-flock-velvet-textured-patterns-blue-suzette-grey-970x970.jpg',
          webcam_block_display_size: '200%',
          webcam_block_repeat: 'no-repeat',
          webcam_block_box_shadow_color: '#3232ff',
          slider_shader_color_1: '#ccccff',
          slider_shader_color_2: '#6666ff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Weather Module: February B',
          month: 'february',
          rule: {
            "dates": [ 2, 6, 7, 13, 17, 22, 23, 26, 27, 29 ]
          },
          face_path: '../img/february/graphicstock-red-velvet-capitone-textile-background-retro-chesterfield-style-checkered-soft-tufted-fabric-furniture-diamond-pattern-decoration-with-buttons-close-up_HLrjhHBjl_thumb.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffff5a',
          face_font_color: '#33330a',
          face_font_shadow_color: '#ffff5a',
          top_path: '../img/february/Velvet_DeepRed_Sample.png',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#33330a',
          top_font_shadow_color: '#ffff5a',
          signal_path: '../img/february/Velvet_DeepRed_Sample.png',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffff5a',
          signal_font_color: '#33330a',
          signal_font_shadow_color: '#ffff5a',
          input_path: '../img/february/31-pink-crushed-velvet-texture.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          zip_user_input_path: '../img/february/31-pink-crushed-velvet-texture.jpg',
          zip_user_input_size: '300%',
          zip_user_input_repeat: 'no-repeat',
          zip_modulator_text_shadow_color: '#ffff5a',
          block_path: '../img/february/31-pink-crushed-velvet-texture.jpg',
          block_size: '300%',
          block_repeat: 'no-repeat',
          block_box_shadow_color: '#ffff5a',
          block_font_color: '#33330a',
          webcam_block_path: '../img/february/31-pink-crushed-velvet-texture.jpg',
          webcam_block_display_size: '200%',
          webcam_block_repeat: 'no-repeat',
          webcam_block_box_shadow_color: '#ffff5a',
          slider_shader_color_1: '#b2b223',
          slider_shader_color_2: '#ffffc1',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Weather Module: February C',
          month: 'february',
          rule: {
            "dates": [ 4, 8, 10, 12, 14, 16, 18, 20, 24, 28 ]
          },
          face_path: '../img/february/actionvance-768441-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffb62f',
          face_font_color: '#191102',
          face_font_shadow_color: '#ffb62f',
          top_path: '../img/february/sharon-mccutcheon-571408-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#191102',
          top_font_shadow_color: '#ffb62f',
          signal_path: '../img/february/sharon-mccutcheon-571408-unsplash.jpg',
          signal_size: '1500%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffb62f',
          signal_font_color: '#191102',
          signal_font_shadow_color: '#ffb62f',
          input_path: '../img/february/david-jorre-477050-unsplash.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          zip_user_input_path: '../img/february/david-jorre-477050-unsplash.jpg',
          zip_user_input_size: '300%',
          zip_user_input_repeat: 'no-repeat',
          zip_modulator_text_shadow_color: '#ffb62f',
          block_path: '../img/february/david-jorre-477050-unsplash.jpg',
          block_size: '300%',
          block_repeat: 'no-repeat',
          block_box_shadow_color: '#ffb62f',
          block_font_color: '#191102',
          webcam_block_path: '../img/february/david-jorre-477050-unsplash.jpg',
          webcam_block_display_size: '200%',
          webcam_block_repeat: 'no-repeat',
          webcam_block_box_shadow_color: '#ffb62f',
          slider_shader_color_1: '#99680f',
          slider_shader_color_2: '#ffe6ba',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('weather_skins_id_seq', (SELECT MAX(id) FROM weather_skins));");
    });
};
