'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('bandpass_filter_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('bandpass_filter_skins').insert([
        {
          id: 1,
          name: 'Bandpass Filter: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 3, 5, 7, 9, 11, 13, 17, 21, 27, 31 ]
          },
          face_path: '../img/january/P1060029.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ccccff',
          face_font_color: '#000019',
          face_font_shadow_color: '#ccccff',
          top_path: '../img/january/icrcrystals2.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#000019',
          top_font_shadow_color: '#ccccff',
          signal_path: '../img/january/icrcrystals2.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ccccff',
          signal_font_color: '#000019',
          signal_font_shadow_color: '#ccccff',
          display_path: '../img/january/D30_5_573_0004_600.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ccccff',
          input_font_color: '#000019',
          input_font_shadow_color: '#ccccff',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ccccff',
          output_font_color: '#000019',
          output_font_shadow_color: '#ccccff',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ccccff',
          frequency_display_font_color: '#000019',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ccccff',
          detune_font_color: '#000019',
          q_size: '300%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#ccccff',
          q_font_color: '#000019',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#3232ff',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Bandpass Filter: January B',
          month: 'january',
          rule: {
            "dates": [ 2, 4, 8, 15, 19, 22, 23, 25, 28, 29 ]
          },
          face_path: '../img/january/thumb_COLOURBOX12738472.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffff32',
          face_font_color: '#333300',
          face_font_shadow_color: '#ffff32',
          top_path: '../img/january/7057940563ddaf3.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#333300',
          top_font_shadow_color: '#ffff32',
          signal_path: '../img/january/7057940563ddaf3.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffff32',
          signal_font_color: '#333300',
          signal_font_shadow_color: '#ffff32',
          display_path: '../img/january/seamless-ice-texture-winter-background-computer-graphic-big-collection-43902505.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ffff32',
          input_font_color: '#333300',
          input_font_shadow_color: '#ffff32',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ffff32',
          output_font_color: '#333300',
          output_font_shadow_color: '#ffff32',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ffff32',
          frequency_display_font_color: '#333300',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ffff32',
          detune_font_color: '#333300',
          q_size: '300%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#ffff32',
          q_font_color: '#333300',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#666600',
          slider_shader_color_2: '#C0C0C0',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Bandpass Filter: January C',
          month: 'january',
          rule: {
            "dates": [ 6, 10, 12, 14, 16, 18, 20, 24, 26, 30 ]
          },
          face_path: '../img/january/fond-ecran-wallpaper-image-fonds-ecran-abstrait-glace-18-1024x640.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff5a5a',
          face_font_color: '#190505',
          face_font_shadow_color: '#ff5a5a',
          top_path: '../img/january/9405440cacd3bd4e755871459556437e.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#190505',
          top_font_shadow_color: '#ff5a5a',
          signal_path: '../img/january/9405440cacd3bd4e755871459556437e.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff5a5a',
          signal_font_color: '#190505',
          signal_font_shadow_color: '#ff5a5a',
          display_path: '../img/january/free-frozen-snow-texture-seamless-and-tileable.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ff5a5a',
          input_font_color: '#190505',
          input_font_shadow_color: '#ff5a5a',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ff5a5a',
          output_font_color: '#190505',
          output_font_shadow_color: '#ff5a5a',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ff5a5a',
          frequency_display_font_color: '#190505',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ff5a5a',
          detune_font_color: '#190505',
          q_size: '300%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#ff5a5a',
          q_font_color: '#190505',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#e52d2d',
          slider_shader_color_2: '#ffeaea',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Bandpass Filter: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 2, 4, 6, 8, 11, 16, 18, 21, 28 ]
          },
          face_path: '../img/february/Red-Silk-Texture1.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#b2b2ef',
          face_font_color: '#000066',
          face_font_shadow_color: '#b2b2ef',
          top_path: '../img/february/Red-Silk-Texture.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#000066',
          top_font_shadow_color: '#b2b2ef',
          signal_path: '../img/february/Red-Silk-Texture.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#b2b2ef',
          signal_font_color: '#000066',
          signal_font_shadow_color: '#b2b2ef',
          display_path: '../img/february/Ivory-Silk-Texture.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#b2b2ef',
          input_font_color: '#000066',
          input_font_shadow_color: '#b2b2ef',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#b2b2ef',
          output_font_color: '#000066',
          output_font_shadow_color: '#b2b2ef',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#b2b2ef',
          frequency_display_font_color: '#000066',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#b2b2ef',
          detune_font_color: '#000066',
          q_size: '300%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#b2b2ef',
          q_font_color: '#000066',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#0000b7',
          slider_shader_color_2: '#e5e5f9',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Bandpass Filter: February B',
          month: 'february',
          rule: {
            "dates": [ 5, 7, 9, 12, 14, 22, 24, 26, 27, 29 ]
          },
          face_path: '../img/february/rawpixel-568387-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#8bff8b',
          face_font_color: '#0c190c',
          face_font_shadow_color: '#8bff8b',
          top_path: '../img/february/background-texture-2110720_1920.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#0c190c',
          top_font_shadow_color: '#8bff8b',
          signal_path: '../img/february/background-texture-2110720_1920.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#8bff8b',
          signal_font_color: '#0c190c',
          signal_font_shadow_color: '#8bff8b',
          display_path: '../img/february/sylvie-tittel-673971-unsplash.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#8bff8b',
          input_font_color: '#0c190c',
          input_font_shadow_color: '#8bff8b',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#8bff8b',
          output_font_color: '#0c190c',
          output_font_shadow_color: '#8bff8b',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#8bff8b',
          frequency_display_font_color: '#0c190c',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#8bff8b',
          detune_font_color: '#0c190c',
          q_size: '300%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#8bff8b',
          q_font_color: '#0c190c',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#326632',
          slider_shader_color_2: '#cbffcb',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Bandpass Filter: February B',
          month: 'february',
          rule: {
            "dates": [ 3, 10, 13, 15, 17, 19, 20, 23, 25 ]
          },
          face_path: '../img/february/fabric-641792_1920.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff5a5a',
          face_font_color: '#190505',
          face_font_shadow_color: '#ff5a5a',
          top_path: '../img/february/weave-3779585_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#190505',
          top_font_shadow_color: '#ff5a5a',
          signal_path: '../img/february/weave-3779585_1920.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff5a5a',
          signal_font_color: '#190505',
          signal_font_shadow_color: '#ff5a5a',
          display_path: '../img/february/wool-433813_1920.jpg',
          input_size: '300%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ff5a5a',
          input_font_color: '#190505',
          input_font_shadow_color: '#ff5a5a',
          output_size: '300%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ff5a5a',
          output_font_color: '#190505',
          output_font_shadow_color: '#ff5a5a',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ff5a5a',
          frequency_display_font_color: '#190505',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ff5a5a',
          detune_font_color: '#190505',
          q_size: '100%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#ff5a5a',
          q_font_color: '#190505',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '200%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#661414',
          slider_shader_color_2: '#ffadad',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('bandpass_filter_skins_id_seq', (SELECT MAX(id) FROM bandpass_filter_skins));");
    });
};
