'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('airlines_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('airlines_skins').insert([
        {
          id: 1,
          name: 'Airlines: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 2, 3, 9, 10, 11, 12, 20, 21, 30, 31 ]
          },
          face_path: '../img/january/in-the-winters-of-south-iceland-you-can-find-otherworldly-blue-ice-caves-1.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff3232',
          face_font_color: '#190000',
          face_font_shadow_color: '#ff3232',
          top_path: '../img/january/26AA74A700000578-2995579-image-a-3_1426414534022.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#190000',
          top_font_shadow_color: '#ff3232',
          signal_path: '../img/january/26AA74A700000578-2995579-image-a-3_1426414534022.jpg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff3232',
          signal_font_color: '#190000',
          signal_font_shadow_color: '#ff3232',
          display_path: '../img/january/iceojo.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ff3232',
          output_font_color: '#190000',
          output_font_shadow_color: '#ff3232',
          flight_table_list_display: '../img/january/iceojo.jpg',
          flight_table_list_size: '200%',
          flight_table_list_repeat: 'no-repeat',
          airline_callsign_display: '../img/january/iceojo.jpg',
          airline_callsign_size: '100%',
          airline_callsign_repeat: 'no-repeat',
          departure_city_data_display: '../img/january/iceojo.jpg',
          departure_city_data_size: '300%',
          departure_city_data_repeat: 'no-repeat',
          arrival_city_data_display: '../img/january/iceojo.jpg',
          arrival_city_data_size: '300%',
          arrival_city_data_repeat: 'no-repeat',
          current_location_display: '../img/january/iceojo.jpg',
          current_location_size: '300%',
          current_location_repeat: 'no-repeat',
          slider_shader_color_1: '#990000',
          slider_shader_color_2: '#ffffff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Airlines: January B',
          month: 'january',
          rule: {
            "dates": [ 4, 7, 8, 13, 19, 22, 23, 24, 28, 29 ]
          },
          face_path: '../img/january/armand-khoury-492456-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#d6d632',
          face_font_color: '#282800',
          face_font_shadow_color: '#d6d632',
          top_path: '../img/january/chuttersnap-334738-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#282800',
          top_font_shadow_color: '#d6d632',
          signal_path: '../img/january/chuttersnap-334738-unsplash.jpg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#d6d632',
          signal_font_color: '#282800',
          signal_font_shadow_color: '#d6d632',
          display_path: '../img/january/aaron-burden-71492-unsplash.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#d6d632',
          output_font_color: '#282800',
          output_font_shadow_color: '#d6d632',
          flight_table_list_display: '../img/january/aaron-burden-71492-unsplash.jpg',
          flight_table_list_size: '200%',
          flight_table_list_repeat: 'no-repeat',
          airline_callsign_display: '../img/january/aaron-burden-71492-unsplash.jpg',
          airline_callsign_size: '100%',
          airline_callsign_repeat: 'no-repeat',
          departure_city_data_display: '../img/january/aaron-burden-71492-unsplash.jpg',
          departure_city_data_size: '300%',
          departure_city_data_repeat: 'no-repeat',
          arrival_city_data_display: '../img/january/aaron-burden-71492-unsplash.jpg',
          arrival_city_data_size: '300%',
          arrival_city_data_repeat: 'no-repeat',
          current_location_display: '../img/january/aaron-burden-71492-unsplash.jpg',
          current_location_size: '300%',
          current_location_repeat: 'no-repeat',
          slider_shader_color_1: '#3d3d00',
          slider_shader_color_2: '#f4f4cc',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Airlines: January C',
          month: 'january',
          rule: {
            "dates": [ 5, 6, 14, 15, 16, 17, 18, 25, 26, 27 ]
          },
          face_path: '../img/january/michael-jasmund-576622-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#81ff81',
          face_font_color: '#071907',
          face_font_shadow_color: '#81ff81',
          top_path: '../img/january/clint-mckoy-666328-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#071907',
          top_font_shadow_color: '#81ff81',
          signal_path: '../img/january/clint-mckoy-666328-unsplash.jpg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#81ff81',
          signal_font_color: '#071907',
          signal_font_shadow_color: '#81ff81',
          display_path: '../img/january/james-ahlberg-723763-unsplash.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#81ff81',
          output_font_color: '#071907',
          output_font_shadow_color: '#81ff81',
          flight_table_list_display: '../img/january/james-ahlberg-723763-unsplash.jpg',
          flight_table_list_size: '200%',
          flight_table_list_repeat: 'no-repeat',
          airline_callsign_display: '../img/january/james-ahlberg-723763-unsplash.jpg',
          airline_callsign_size: '100%',
          airline_callsign_repeat: 'no-repeat',
          departure_city_data_display: '../img/january/james-ahlberg-723763-unsplash.jpg',
          departure_city_data_size: '300%',
          departure_city_data_repeat: 'no-repeat',
          arrival_city_data_display: '../img/january/james-ahlberg-723763-unsplash.jpg',
          arrival_city_data_size: '300%',
          arrival_city_data_repeat: 'no-repeat',
          current_location_display: '../img/january/james-ahlberg-723763-unsplash.jpg',
          current_location_size: '300%',
          current_location_repeat: 'no-repeat',
          slider_shader_color_1: '#1e661e',
          slider_shader_color_2: '#c9ffc9',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Airlines: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 3, 5, 7, 9, 11, 13, 21, 23 ]
          },
          face_path: '../img/february/texture-1162641_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#81ff81',
          face_font_color: '#071907',
          face_font_shadow_color: '#81ff81',
          top_path: '../img/february/glass-1737571_1280.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#071907',
          top_font_shadow_color: '#81ff81',
          signal_path: '../img/february/glass-1737571_1280.jpg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#81ff81',
          signal_font_color: '#071907',
          signal_font_shadow_color: '#81ff81',
          display_path: '../img/february/pattern-3263624_1920.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#81ff81',
          output_font_color: '#071907',
          output_font_shadow_color: '#81ff81',
          flight_table_list_display: '../img/february/pattern-3263624_1920.jpg',
          flight_table_list_size: '200%',
          flight_table_list_repeat: 'no-repeat',
          airline_callsign_display: '../img/february/pattern-3263624_1920.jpg',
          airline_callsign_size: '100%',
          airline_callsign_repeat: 'no-repeat',
          departure_city_data_display: '../img/february/pattern-3263624_1920.jpg',
          departure_city_data_size: '300%',
          departure_city_data_repeat: 'no-repeat',
          arrival_city_data_display: '../img/february/pattern-3263624_1920.jpg',
          arrival_city_data_size: '300%',
          arrival_city_data_repeat: 'no-repeat',
          current_location_display: '../img/february/pattern-3263624_1920.jpg',
          current_location_size: '300%',
          current_location_repeat: 'no-repeat',
          slider_shader_color_1: '#1e661e',
          slider_shader_color_2: '#c9ffc9',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Airlines: February B',
          month: 'february',
          rule: {
            "dates": [ 2, 4, 6, 15, 17, 22, 24, 25, 27, 29 ]
          },
          face_path: '../img/february/quilting-2581992_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#8484d0',
          face_font_color: '#0a0a23',
          face_font_shadow_color: '#8484d0',
          top_path: '../img/february/fabric-3543777_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#0a0a23',
          top_font_shadow_color: '#8484d0',
          signal_path: '../img/february/fabric-3543777_1920.jpg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#8484d0',
          signal_font_color: '#0a0a23',
          signal_font_shadow_color: '#8484d0',
          display_path: '../img/february/fabric-3310827_1280.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#8484d0',
          output_font_color: '#0a0a23',
          output_font_shadow_color: '#8484d0',
          flight_table_list_display: '../img/february/fabric-3310827_1280.jpg',
          flight_table_list_size: '200%',
          flight_table_list_repeat: 'no-repeat',
          airline_callsign_display: '../img/february/fabric-3310827_1280.jpg',
          airline_callsign_size: '100%',
          airline_callsign_repeat: 'no-repeat',
          departure_city_data_display: '../img/february/fabric-3310827_1280.jpg',
          departure_city_data_size: '300%',
          departure_city_data_repeat: 'no-repeat',
          arrival_city_data_display: '../img/february/fabric-3310827_1280.jpg',
          arrival_city_data_size: '300%',
          arrival_city_data_repeat: 'no-repeat',
          current_location_display: '../img/february/fabric-3310827_1280.jpg',
          current_location_size: '300%',
          current_location_repeat: 'no-repeat',
          slider_shader_color_1: '#191959',
          slider_shader_color_2: '#c1c1e7',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Airlines: February C',
          month: 'february',
          rule: {
            "dates": [ 8, 10, 12, 14, 16, 18, 19, 20, 26, 28 ]
          },
          face_path: '../img/february/575863788b0c375.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#e73838',
          face_font_color: '#2d0707',
          face_font_shadow_color: '#e73838',
          top_path: '../img/february/fabric-texture-abstract-art-pattern-cloth-design-brown-leaf-5-500x375.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#2d0707',
          top_font_shadow_color: '#e73838',
          signal_path: '../img/february/fabric-texture-abstract-art-pattern-cloth-design-brown-leaf-5-500x375.jpg',
          signal_size: '1600%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#e73838',
          signal_font_color: '#2d0707',
          signal_font_shadow_color: '#e73838',
          display_path: '../img/february/0458622a27da77c.jpg',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#e73838',
          output_font_color: '#2d0707',
          output_font_shadow_color: '#e73838',
          flight_table_list_display: '../img/february/0458622a27da77c.jpg',
          flight_table_list_size: '200%',
          flight_table_list_repeat: 'no-repeat',
          airline_callsign_display: '../img/february/0458622a27da77c.jpg',
          airline_callsign_size: '100%',
          airline_callsign_repeat: 'no-repeat',
          departure_city_data_display: '../img/february/0458622a27da77c.jpg',
          departure_city_data_size: '300%',
          departure_city_data_repeat: 'no-repeat',
          arrival_city_data_display: '../img/february/0458622a27da77c.jpg',
          arrival_city_data_size: '300%',
          arrival_city_data_repeat: 'no-repeat',
          current_location_display: '../img/february/0458622a27da77c.jpg',
          current_location_size: '300%',
          current_location_repeat: 'no-repeat',
          slider_shader_color_1: '#5b0e0e',
          slider_shader_color_2: '#f7bdbd',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('airlines_skins_id_seq', (SELECT MAX(id) FROM airlines_skins));");
    });
};
