'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('highshelf_filter_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('highshelf_filter_skins').insert([
        {
          id: 1,
          name: 'Highshelf Filter: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 2, 4, 6, 9, 11, 14, 16, 21, 24, 31 ]
          },
          face_path: '../img/january/daria-volkova-479878-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#db4c4c',
          face_font_color: '#140000',
          face_font_shadow_color: '#db4c4c',
          top_path: '../img/january/christian-regg-534492-unsplash.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#140000',
          top_font_shadow_color: '#db4c4c',
          signal_path: '../img/january/christian-regg-534492-unsplash.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#db4c4c',
          signal_font_color: '#140000',
          signal_font_shadow_color: '#db4c4c',
          display_path: '../img/january/paula-schutte-518033-unsplash.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#db4c4c',
          input_font_color: '#140000',
          input_font_shadow_color: '#db4c4c',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#db4c4c',
          output_font_color: '#140000',
          output_font_shadow_color: '#db4c4c',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#db4c4c',
          frequency_display_font_color: '#140000',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#db4c4c',
          detune_font_color: '#140000',
          gain_size: '300%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#db4c4c',
          gain_font_color: '#140000',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#f4cccc',
          slider_shader_color_2: '#8e0000',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Highshelf Filter: January B',
          month: 'january',
          rule: {
            "dates": [ 5, 7, 10, 12, 19, 22, 25, 26, 27, 29 ]
          },
          face_path: '../img/january/laurent-naville-764505-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#8484ff',
          face_font_color: '#050519',
          face_font_shadow_color: '#8484ff',
          top_path: '../img/january/nathan-anderson-223103-unsplash.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#050519',
          top_font_shadow_color: '#8484ff',
          signal_path: '../img/january/nathan-anderson-223103-unsplash.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#8484ff',
          signal_font_color: '#050519',
          signal_font_shadow_color: '#8484ff',
          display_path: '../img/january/heather-shevlin-369400-unsplash.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#8484ff',
          input_font_color: '#050519',
          input_font_shadow_color: '#8484ff',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#8484ff',
          output_font_color: '#050519',
          output_font_shadow_color: '#8484ff',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#8484ff',
          frequency_display_font_color: '#050519',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#8484ff',
          detune_font_color: '#050519',
          gain_size: '300%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#8484ff',
          gain_font_color: '#050519',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#4646ff',
          slider_shader_color_2: '#d6d6ff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Highshelf Filter: January C',
          month: 'january',
          rule: {
            "dates": [ 3, 8, 13, 15, 17, 18, 20, 23, 28, 30 ]
          },
          face_path: '../img/january/ice-3436478_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ea3232',
          face_font_color: '#2d0000',
          face_font_shadow_color: '#ea3232',
          top_path: '../img/january/ice-crystals-3425159_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#2d0000',
          top_font_shadow_color: '#ea3232',
          signal_path: '../img/january/ice-crystals-3425159_1920.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ea3232',
          signal_font_color: '#2d0000',
          signal_font_shadow_color: '#ea3232',
          display_path: '../img/january/ice-3272344_1920.jpg',
          input_size: '300%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ea3232',
          input_font_color: '#2d0000',
          input_font_shadow_color: '#ea3232',
          output_size: '300%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ea3232',
          output_font_color: '#2d0000',
          output_font_shadow_color: '#ea3232',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ea3232',
          frequency_display_font_color: '#2d0000',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ea3232',
          detune_font_color: '#2d0000',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#ea3232',
          gain_font_color: '#2d0000',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#720000',
          slider_shader_color_2: '#f49999',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Highshelf Filter: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 2, 5, 6, 8, 11, 15, 18, 21, 25 ]
          },
          face_path: '../img/february/jeans-2411741_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#b8dc6f',
          face_font_color: '#0f1405',
          face_font_shadow_color: '#b8dc6f',
          top_path: '../img/february/attractive-3671905_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#0f1405',
          top_font_shadow_color: '#b8dc6f',
          signal_path: '../img/february/attractive-3671905_1920.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#b8dc6f',
          signal_font_color: '#0f1405',
          signal_font_shadow_color: '#b8dc6f',
          display_path: '../img/february/white-2592448_1920.jpg',
          input_size: '300%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#b8dc6f',
          input_font_color: '#0f1405',
          input_font_shadow_color: '#b8dc6f',
          output_size: '300%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#b8dc6f',
          output_font_color: '#0f1405',
          output_font_shadow_color: '#b8dc6f',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#b8dc6f',
          frequency_display_font_color: '#0f1405',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#b8dc6f',
          detune_font_color: '#0f1405',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#b8dc6f',
          gain_font_color: '#0f1405',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#e0f0c1',
          slider_shader_color_2: '#3d5214',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Highshelf Filter: February B',
          month: 'february',
          rule: {
            "dates": [ 3, 7, 9, 12, 16, 22, 23, 26, 27, 28 ]
          },
          face_path: '../img/february/00674201012010348233030.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#f3f31c',
          face_font_color: '#181800',
          face_font_shadow_color: '#f3f31c',
          top_path: '../img/february/bed-sheet-texture-cozy-1314710560-graffiti-line-grigio-30x60-2.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#181800',
          top_font_shadow_color: '#f3f31c',
          signal_path: '../img/february/bed-sheet-texture-cozy-1314710560-graffiti-line-grigio-30x60-2.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#f3f31c',
          signal_font_color: '#181800',
          signal_font_shadow_color: '#f3f31c',
          display_path: '../img/february/pindler-diedre-net-fabric-cream-remodelista.jpg',
          input_size: '300%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#f3f31c',
          input_font_color: '#181800',
          input_font_shadow_color: '#f3f31c',
          output_size: '300%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#f3f31c',
          output_font_color: '#181800',
          output_font_shadow_color: '#f3f31c',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#f3f31c',
          frequency_display_font_color: '#181800',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#f3f31c',
          detune_font_color: '#181800',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#f3f31c',
          gain_font_color: '#181800',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#484800',
          slider_shader_color_2: '#f7f767',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Highshelf Filter: February C',
          month: 'february',
          rule: {
            "dates": [ 4, 10, 13, 14, 17, 19, 20, 24, 29 ]
          },
          face_path: '../img/february/jeans-2654861_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#c32a2a',
          face_font_color: '#130404',
          face_font_shadow_color: '#c32a2a',
          top_path: '../img/february/fabric-2418463_1920.jpg',
          top_size: '130%',
          top_repeat: 'no-repeat',
          top_font_color: '#130404',
          top_font_shadow_color: '#c32a2a',
          signal_path: '../img/february/fabric-2418463_1920.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#c32a2a',
          signal_font_color: '#130404',
          signal_font_shadow_color: '#c32a2a',
          display_path: '../img/february/fabric-3709211_1920.jpg',
          input_size: '300%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#c32a2a',
          input_font_color: '#130404',
          input_font_shadow_color: '#c32a2a',
          output_size: '300%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#c32a2a',
          output_font_color: '#130404',
          output_font_shadow_color: '#c32a2a',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#c32a2a',
          frequency_display_font_color: '#130404',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#c32a2a',
          detune_font_color: '#130404',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#c32a2a',
          gain_font_color: '#130404',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#4e1010',
          slider_shader_color_2: '#d56969',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('highshelf_filter_skins_id_seq', (SELECT MAX(id) FROM highshelf_filter_skins));");
    });
};
