'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('peaking_filter_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('peaking_filter_skins').insert([
        {
          id: 1,
          name: 'Peaking Filter: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 2, 3, 4, 5, 11, 12, 13, 21, 22, 31 ]
          },
          face_path: '../img/january/joyce-mccown-766494-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffff5a',
          face_font_color: '#4c4c0f',
          face_font_shadow_color: '#ffff5a',
          top_path: '../img/january/asoggetti-529827-unsplash.jpg',
          top_size: '110%',
          top_repeat: 'no-repeat',
          top_font_color: '#4c4c0f',
          top_font_shadow_color: '#ffff5a',
          signal_path: '../img/january/asoggetti-529827-unsplash.jpg',
          signal_size: '2000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffff5a',
          signal_font_color: '#4c4c0f',
          signal_font_shadow_color: '#ffff5a',
          display_path: '../img/january/michael-aleo-571962-unsplash.jpg',
          input_size: '600%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ffff5a',
          input_font_color: '#4c4c0f',
          input_font_shadow_color: '#ffff5a',
          output_size: '600%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ffff5a',
          output_font_color: '#4c4c0f',
          output_font_shadow_color: '#ffff5a',
          frequency_display_size: '300%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ffff5a',
          frequency_display_font_color: '#4c4c0f',
          detune_size: '300%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ffff5a',
          detune_font_color: '#4c4c0f',
          q_size: '300%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#ffff5a',
          q_font_color: '#4c4c0f',
          gain_size: '300%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#ffff5a',
          gain_font_color: '#4c4c0f',
          mod_select_size: '300%',
          mod_repeat_value: 'no-repeat',
          slider_size: '300%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#ffff32',
          slider_shader_color_2: '#ffffd6',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Peaking Filter: January B',
          month: 'january',
          rule: {
            "dates": [ 6, 7, 8, 14, 15, 23, 24, 25, 26, 27 ]
          },
          face_path: '../img/january/ice-2834617_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#a3a3ff',
          face_font_color: '#050533',
          face_font_shadow_color: '#a3a3ff',
          top_path: '../img/january/freeze-1942957_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#050533',
          top_font_shadow_color: '#a3a3ff',
          signal_path: '../img/january/freeze-1942957_1920.jpg',
          signal_size: '3000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#a3a3ff',
          signal_font_color: '#050533',
          signal_font_shadow_color: '#a3a3ff',
          display_path: '../img/january/nature-2570547_1920.jpg',
          input_size: '200%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#a3a3ff',
          input_font_color: '#050533',
          input_font_shadow_color: '#a3a3ff',
          output_size: '200%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#a3a3ff',
          output_font_color: '#050533',
          output_font_shadow_color: '#a3a3ff',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#a3a3ff',
          frequency_display_font_color: '#050533',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#a3a3ff',
          detune_font_color: '#050533',
          q_size: '100%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#a3a3ff',
          q_font_color: '#050533',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#a3a3ff',
          gain_font_color: '#050533',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#0a0a66',
          slider_shader_color_2: '#d1d1ff',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Peaking Filter: January C',
          month: 'january',
          rule: {
            "dates": [ 9, 10, 16, 17, 18, 19, 20, 28, 29, 30 ]
          },
          face_path: '../img/january/ghost-presenter-1180102-unsplash.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ffff00',
          face_font_color: '#191900',
          face_font_shadow_color: '#ffff00',
          top_path: '../img/january/ghost-presenter-1180091-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#191900',
          top_font_shadow_color: '#ffff00',
          signal_path: '../img/january/ghost-presenter-1180091-unsplash.jpg',
          signal_size: '3000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ffff00',
          signal_font_color: '#191900',
          signal_font_shadow_color: '#ffff00',
          display_path: '../img/january/pascal-mauerhofer-424300-unsplash.jpg',
          input_size: '200%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ffff00',
          input_font_color: '#191900',
          input_font_shadow_color: '#ffff00',
          output_size: '200%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ffff00',
          output_font_color: '#191900',
          output_font_shadow_color: '#ffff00',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ffff00',
          frequency_display_font_color: '#191900',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ffff00',
          detune_font_color: '#191900',
          q_size: '100%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#ffff00',
          q_font_color: '#191900',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#ffff00',
          gain_font_color: '#191900',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#4c4c00',
          slider_shader_color_2: '#ffff66',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Peaking Filter: February A',
          month: 'february',
          rule: {
            "dates": [ 1, 3, 5, 7, 9, 11, 13, 15, 21, 23 ]
          },
          face_path: '../img/february/fabric-texture-44.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#4545f0',
          face_font_color: '#060618',
          face_font_shadow_color: '#4545f0',
          top_path: '../img/february/textile-texture0029-e1445257511298.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#060618',
          top_font_shadow_color: '#4545f0',
          signal_path: '../img/february/textile-texture0029-e1445257511298.jpg',
          signal_size: '3000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#4545f0',
          signal_font_color: '#060618',
          signal_font_shadow_color: '#4545f0',
          display_path: '../img/february/fabric-by-the-yard-textured-basketweave-o.jpg',
          input_size: '200%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#4545f0',
          input_font_color: '#060618',
          input_font_shadow_color: '#4545f0',
          output_size: '200%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#4545f0',
          output_font_color: '#060618',
          output_font_shadow_color: '#4545f0',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#4545f0',
          frequency_display_font_color: '#060618',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#4545f0',
          detune_font_color: '#060618',
          q_size: '100%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#4545f0',
          q_font_color: '#060618',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#4545f0',
          gain_font_color: '#060618',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#222278',
          slider_shader_color_2: '#b4b4f9',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Peaking Filter: February B',
          month: 'february',
          rule: {
            "dates": [ 2, 4, 6, 17, 19, 22, 24, 25, 27, 29 ]
          },
          face_path: '../img/february/background-1904289_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff81c0',
          face_font_color: '#190c13',
          face_font_shadow_color: '#ff81c0',
          top_path: '../img/february/cloth-6123_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#190c13',
          top_font_shadow_color: '#ff81c0',
          signal_path: '../img/february/cloth-6123_1920.jpg',
          signal_size: '3000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff81c0',
          signal_font_color: '#190c13',
          signal_font_shadow_color: '#ff81c0',
          display_path: '../img/february/woven-2607340_1920.jpg',
          input_size: '200%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ff81c0',
          input_font_color: '#190c13',
          input_font_shadow_color: '#ff81c0',
          output_size: '200%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ff81c0',
          output_font_color: '#190c13',
          output_font_shadow_color: '#ff81c0',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#ff81c0',
          frequency_display_font_color: '#190c13',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#ff81c0',
          detune_font_color: '#190c13',
          q_size: '100%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#ff81c0',
          q_font_color: '#190c13',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#ff81c0',
          gain_font_color: '#190c13',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#66334c',
          slider_shader_color_2: '#ffa6d2',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Peaking Filter: February C',
          month: 'february',
          rule: {
            "dates": [ 8, 10, 12, 14, 16, 18, 20, 26, 28 ]
          },
          face_path: '../img/february/Feature-image-696x464.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#f95018',
          face_font_color: '#060618',
          face_font_shadow_color: '#f95018',
          top_path: '../img/february/negative-space-woven-fabric-texture-wallpaper-1062x708.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#060618',
          top_font_shadow_color: '#f95018',
          signal_path: '../img/february/negative-space-woven-fabric-texture-wallpaper-1062x708.jpg',
          signal_size: '3000%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#f95018',
          signal_font_color: '#060618',
          signal_font_shadow_color: '#f95018',
          display_path: '../img/february/fabric_texture_pbr_2k_pack_96_dpi_2048_in_2048_high_23jpg_3d_model_c4d_max_obj_fbx_ma_lwo_3ds_3dm_stl_2305307_o.jpg',
          input_size: '200%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#f95018',
          input_font_color: '#060618',
          input_font_shadow_color: '#f95018',
          output_size: '200%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#f95018',
          output_font_color: '#060618',
          output_font_shadow_color: '#f95018',
          frequency_display_size: '100%',
          frequency_display_repeat: 'no-repeat',
          frequency_display_box_shadow_color: '#f95018',
          frequency_display_font_color: '#060618',
          detune_size: '100%',
          detune_repeat: 'no-repeat',
          detune_box_shadow_color: '#f95018',
          detune_font_color: '#060618',
          q_size: '100%',
          q_repeat: 'no-repeat',
          q_box_shadow_color: '#f95018',
          q_font_color: '#060618',
          gain_size: '100%',
          gain_repeat: 'no-repeat',
          gain_box_shadow_color: '#f95018',
          gain_font_color: '#060618',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_size: '100%',
          slide_repeat_value: 'no-repeat',
          slider_shader_color_1: '#7c280c',
          slider_shader_color_2: '#fb9674',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('peaking_filter_skins_id_seq', (SELECT MAX(id) FROM peaking_filter_skins));");
    });
};
