'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('delay_skins').del()
    .then(function () {
      // Inserts seed entries
      return knex('delay_skins').insert([
        {
          id: 1,
          name: 'Delay: January A',
          month: 'january',
          rule: {
            "dates": [ 1, 2, 4, 7, 10, 11, 12, 14, 21, 22, 31 ]
          },
          face_path: '../img/january/wallpaper-2094453_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#5dff5d',
          face_font_color: '#0f330f',
          face_font_shadow_color: '#5dff5d',
          top_path: '../img/january/water-3191773_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#0f330f',
          top_font_shadow_color: '#5dff5d',
          signal_path: '../img/january/water-3191773_1920.jpg',
          signal_size: '1100%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#5dff5d',
          signal_font_color: '#0f330f',
          signal_font_shadow_color: '#5dff5d',
          display_path: '../img/january/sculpture-142471_1920.jpg',
          input_size: '400%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#5dff5d',
          input_font_color: '#0f330f',
          input_font_shadow_color: '#5dff5d',
          output_size: '400%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#5dff5d',
          output_font_color: '#0f330f',
          output_font_shadow_color: '#5dff5d',
          delay_display_size: '100%',
          delay_display_repeat: 'no-repeat',
          delay_display_box_shadow_color: '#5dff5d',
          delay_display_font_color: '#0f330f',
          delay_slider_size: '100%',
          delay_slider_repeat: 'no-repeat',
          delay_slider_box_shadow_color: '#5dff5d',
          delay_slider_font_color: '#0f330f',
          mod_select_size: '200%',
          mod_repeat_value: 'no-repeat',
          slider_shader_color_1: '#1e661e',
          slider_shader_color_2: '#dbffdb',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 2,
          name: 'Delay: January B',
          month: 'january',
          rule: {
            "dates": [ 3, 5, 6, 17, 20, 23, 24, 25, 27, 30 ]
          },
          face_path: '../img/january/ice-floes-56765_1920.jpg',
          face_size: '100%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#ff1919',
          face_font_color: '#190000',
          face_font_shadow_color: '#ff1919',
          top_path: '../img/january/water-285431_1920.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#190000',
          top_font_shadow_color: '#ff1919',
          signal_path: '../img/january/water-285431_1920.jpg',
          signal_size: '1100%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#ff1919',
          signal_font_color: '#190000',
          signal_font_shadow_color: '#ff1919',
          display_path: '../img/january/ice-1092875_1280.jpg',
          input_size: '400%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#ff1919',
          input_font_color: '#190000',
          input_font_shadow_color: '#ff1919',
          output_size: '400%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#ff1919',
          output_font_color: '#190000',
          output_font_shadow_color: '#ff1919',
          delay_display_size: '100%',
          delay_display_repeat: 'no-repeat',
          delay_display_box_shadow_color: '#ff1919',
          delay_display_font_color: '#190000',
          delay_slider_size: '100%',
          delay_slider_repeat: 'no-repeat',
          delay_slider_box_shadow_color: '#ff1919',
          delay_slider_font_color: '#190000',
          mod_select_size: '200%',
          mod_repeat_value: 'no-repeat',
          slider_shader_color_1: '#660000',
          slider_shader_color_2: '#ff7f7f',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 3,
          name: 'Delay: January B',
          month: 'january',
          rule: {
            "dates": [ 8, 9, 13, 15, 16, 18, 19, 26, 28, 29 ]
          },
          face_path: '../img/january/dirk-spijkers-690776-unsplash.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#81ff81',
          face_font_color: '#0f330f',
          face_font_shadow_color: '#81ff81',
          top_path: '../img/january/holger-link-773325-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#0f330f',
          top_font_shadow_color: '#81ff81',
          signal_path: '../img/january/holger-link-773325-unsplash.jpg',
          signal_size: '1100%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#81ff81',
          signal_font_color: '#0f330f',
          signal_font_shadow_color: '#81ff81',
          display_path: '../img/january/dirk-spijkers-690775-unsplash.jpg',
          input_size: '400%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#81ff81',
          input_font_color: '#0f330f',
          input_font_shadow_color: '#81ff81',
          output_size: '400%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#81ff81',
          output_font_color: '#0f330f',
          output_font_shadow_color: '#81ff81',
          delay_display_size: '100%',
          delay_display_repeat: 'no-repeat',
          delay_display_box_shadow_color: '#81ff81',
          delay_display_font_color: '#0f330f',
          delay_slider_size: '85%',
          delay_slider_repeat: 'no-repeat',
          delay_slider_box_shadow_color: '#81ff81',
          delay_slider_font_color: '#0f330f',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_shader_color_1: '#1e661e',
          slider_shader_color_2: '#c9ffc9',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 4,
          name: 'Delay: February B',
          month: 'february',
          rule: {
            "dates": [ 1, 3, 4, 6, 7, 11, 13, 14, 21, 23 ]
          },
          face_path: '../img/february/sharon-mccutcheon-678348-unsplash.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#f63b3b',
          face_font_color: '#180505',
          face_font_shadow_color: '#f63b3b',
          top_path: '../img/february/siora-photography-1115165-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#180505',
          top_font_shadow_color: '#f63b3b',
          signal_path: '../img/february/siora-photography-1115165-unsplash.jpg',
          signal_size: '1100%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#f63b3b',
          signal_font_color: '#180505',
          signal_font_shadow_color: '#f63b3b',
          display_path: '../img/february/sylvie-tittel-977040-unsplash.jpg',
          input_size: '400%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#f63b3b',
          input_font_color: '#180505',
          input_font_shadow_color: '#f63b3b',
          output_size: '400%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#f63b3b',
          output_font_color: '#180505',
          output_font_shadow_color: '#f63b3b',
          delay_display_size: '100%',
          delay_display_repeat: 'no-repeat',
          delay_display_box_shadow_color: '#f63b3b',
          delay_display_font_color: '#180505',
          delay_slider_size: '85%',
          delay_slider_repeat: 'no-repeat',
          delay_slider_box_shadow_color: '#f63b3b',
          delay_slider_font_color: '#180505',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_shader_color_1: '#491111',
          slider_shader_color_2: '#f87575',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 5,
          name: 'Delay: February B',
          month: 'february',
          rule: {
            "dates": [ 2, 5, 9, 16, 17, 22, 24, 26, 27, 29 ]
          },
          face_path: '../img/february/fabric-texture-1-1.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#31df69',
          face_font_color: '#092c15',
          face_font_shadow_color: '#31df69',
          top_path: '../img/february/lee.jofa.jumper.in.toast.textiles.textiles.fabrics.texture.cotton.cotton.blend.synthetic.1496954115.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#092c15',
          top_font_shadow_color: '#31df69',
          signal_path: '../img/february/lee.jofa.jumper.in.toast.textiles.textiles.fabrics.texture.cotton.cotton.blend.synthetic.1496954115.jpg',
          signal_size: '1100%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#31df69',
          signal_font_color: '#092c15',
          signal_font_shadow_color: '#31df69',
          display_path: '../img/february/woven-2607340_960_720.jpg',
          input_size: '400%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#31df69',
          input_font_color: '#092c15',
          input_font_shadow_color: '#31df69',
          output_size: '400%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#31df69',
          output_font_color: '#092c15',
          output_font_shadow_color: '#31df69',
          delay_display_size: '110%',
          delay_display_repeat: 'no-repeat',
          delay_display_box_shadow_color: '#31df69',
          delay_display_font_color: '#092c15',
          delay_slider_size: '120%',
          delay_slider_repeat: 'no-repeat',
          delay_slider_box_shadow_color: '#31df69',
          delay_slider_font_color: '#092c15',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_shader_color_1: '#13592a',
          slider_shader_color_2: '#83eba5',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        },
        {
          id: 6,
          name: 'Delay: February B',
          month: 'february',
          rule: {
            "dates": [ 8, 10, 12, 15, 18, 19, 20, 25, 28 ]
          },
          face_path: '../img/february/sharon-mccutcheon-MIb2S5z8VJo-unsplash.jpg',
          face_size: '110%',
          face_repeat: 'no-repeat',
          face_box_shadow_color: '#73f6df',
          face_font_color: '#0b1816',
          face_font_shadow_color: '#73f6df',
          top_path: '../img/february/sonya-eliseeva-7NohkaKbROU-unsplash.jpg',
          top_size: '100%',
          top_repeat: 'no-repeat',
          top_font_color: '#0b1816',
          top_font_shadow_color: '#73f6df',
          signal_path: '../img/february/sonya-eliseeva-7NohkaKbROU-unsplash.jpg',
          signal_size: '1100%',
          signal_repeat: 'no-repeat',
          signal_box_shadow_color: '#73f6df',
          signal_font_color: '#0b1816',
          signal_font_shadow_color: '#73f6df',
          display_path: '../img/february/sharon-mccutcheon-XeEvy_ofGNk-unsplash.jpg',
          input_size: '400%',
          input_repeat: 'no-repeat',
          input_box_shadow_color: '#73f6df',
          input_font_color: '#0b1816',
          input_font_shadow_color: '#73f6df',
          output_size: '400%',
          output_repeat: 'no-repeat',
          output_box_shadow_color: '#73f6df',
          output_font_color: '#0b1816',
          output_font_shadow_color: '#73f6df',
          delay_display_size: '110%',
          delay_display_repeat: 'no-repeat',
          delay_display_box_shadow_color: '#73f6df',
          delay_display_font_color: '#0b1816',
          delay_slider_size: '120%',
          delay_slider_repeat: 'no-repeat',
          delay_slider_box_shadow_color: '#73f6df',
          delay_slider_font_color: '#0b1816',
          mod_select_size: '100%',
          mod_repeat_value: 'no-repeat',
          slider_shader_color_1: '#17312c',
          slider_shader_color_2: '#8ff7e5',
          created_at: new Date('2017-07-20T13:44:00.000Z'),
          updated_at: new Date('2017-07-20T13:44:00.000Z')
        }
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('delay_skins_id_seq', (SELECT MAX(id) FROM delay_skins));");
    });
};
